# Cluster configuration generated by NICO
# This file is automatically generated - do not edit manually

{
  # Cluster name
  name = "home-prod";

  # Virtual IP for HA control plane
  vip = "192.168.1.100";

  # Cluster token for k3s
  clusterToken = "k3s-cluster-token-secret-12345";

  # Control plane nodes with IP addresses
  controlPlane = [
    { name = "cp-01"; ip = "192.168.1.101"; }
    { name = "cp-02"; ip = "192.168.1.102"; }
    { name = "cp-03"; ip = "192.168.1.103"; }
  ];

  # Worker nodes with IP addresses
  workers = [
    { name = "worker-01"; ip = "192.168.1.201"; }
    { name = "worker-02"; ip = "192.168.1.202"; }
  ];
}
