apiVersion: nico.homystack.com/v1alpha1
kind: KubernetesCluster
metadata:
  name: home-prod
  namespace: default
spec:
  controlPlane:
    count: 1

  # Git repository with cluster flakes
  gitRepo: "https://github.com/homystack/nico.git"
  ref: "master"
  configurationSubdir: "nix"
